apiVersion: v1
kind: Service
metadata:
  name: devops-takehome
  labels:
    app: devops-takehome
spec:
  type: LoadBalancer
  ports:
   - port: 80
  selector:
   app: devops-takehome

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-takehome
spec:
  replicas: $num_replicas
  template:
    metadata:
      labels:
        app: devops-takehome
    spec:
      containers:
        - name: devops-takehome
          image: 337546869648.dkr.ecr.us-east-1.amazonaws.com/devops-takehome:$tag
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:test123@postgres:5432/groundspeed_devops
